[package]
name = "kcash"
version = "1.0.0"
authors = []

[addresses]
KCashAdmin = "_"

[dev-addresses]
KCashAdmin = '0x5bd5d55eefa9caf9fcd983e56f1b85871a516d0ab4b85a3c999f7de5059e4744'

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'
