[package]
name = "PoGNFT"
version = "1.0.0"
authors = []

[addresses]
KGeN = "0x850a31e0b352c359ea24ffd17582081d766f82ea2ddea7a888b9cdcb30a3e7a7"

[dev-addresses]
KGeNPOG = "0xc0343ea7f708085bf6505eaa10f339b6412e924cbdd6cdc5cc9d95d38eec3099"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dependencies.kgen_oracle_package]
local = '../oracle-network'

[dev-dependencies]
